import assert from "node:assert/strict";
import test from "node:test";
import { analyzePredictiveHealth, detectHealthPatterns, type HealthDay } from "./predictive-solar-health";

function days(ratios: number[], options: Partial<HealthDay> = {}): HealthDay[] { return ratios.map((ratio, index) => ({ time: Date.parse("2026-06-01T12:00:00Z") + index * 86400000, expectedKwh: 30, actualKwh: 30 * ratio, ratio, validSamples: 60, expectedSamples: 144, clearSamples: 50, cloudySamples: 2, rainSamples: 0, hotSamples: 0, faultSamples: 0, offlineSamples: 0, ...options })); }
test("stable normalized performance is healthy", () => { const result = analyzePredictiveHealth(days([.96,.95,.97,.96,.95,.96,.95])); assert.equal(result.status, "healthy"); assert.equal(result.direction, "stable"); });
test("gradual normalized decline produces an early warning", () => { const result = analyzePredictiveHealth(days([.96,.95,.94,.92,.90,.89,.87])); assert.equal(result.status, "early_warning"); assert.equal(result.direction, "declining"); });
test("cloud-heavy decline ranks weather above degradation", () => { const result = analyzePredictiveHealth(days([.96,.95,.93,.90,.87,.84,.82], { clearSamples: 5, cloudySamples: 50 })); assert.equal(result.causes[0].cause, "weather"); assert.ok((result.causes.find((cause) => cause.cause === "inverter_degradation")?.score ?? 0) < result.causes[0].score); });
test("performance recovery after recorded cleaning increases soiling evidence", () => { const input = days([.85,.83,.82,.94,.95,.94]); const result = analyzePredictiveHealth(input, [{ id:"1", time: input[3].time, type:"panels_cleaned" }]); assert.equal(result.causes[0].cause, "soiling"); assert.ok(result.causes[0].score >= .85); });
test("repeated afternoon clear-weather drops detect shading", () => { const base = Date.parse("2026-06-01T16:00:00"); const samples = [0,1,2].map((day) => ({ time: base + day*86400000, expectedKw: 4, actualKw: 2, irradiance: 800, cloudCover: 10, rain: false })); const pattern = detectHealthPatterns(samples); assert.equal(pattern.recurringShading, true); assert.equal(pattern.recurringHour, 16); });
test("sudden drop with inverter faults is critical", () => { const result = analyzePredictiveHealth(days([.95,.94,.93,.2], { faultSamples: 2 })); assert.equal(result.status, "building_baseline"); const long = analyzePredictiveHealth(days([.95,.95,.94,.94,.94,.94,.94,.2], { faultSamples: 2 })); assert.equal(long.status, "critical"); assert.equal(long.causes[0].cause, "inverter_fault"); });
test("large historical gaps produce insufficient data", () => { const sparse = days([.95,.94,.93,.92,.91,.9,.89]).map((day, index) => ({ ...day, time: day.time + index * 5 * 86400000, validSamples: 4 })); assert.equal(analyzePredictiveHealth(sparse).status, "insufficient_data"); });
test("offline samples indicate communication rather than panel failure", () => { const result = analyzePredictiveHealth(days([.95,.95,.95,.95,.95,.95,.95], { offlineSamples: 8 })); assert.ok(result.causes.some((cause) => cause.cause === "communication_issue" && cause.score > .5)); assert.ok(!result.causes.some((cause) => cause.cause === "panel_degradation" && cause.score > .5)); });
test("high temperature is an explanation rather than an inverter fault", () => { const result = analyzePredictiveHealth(days([.95,.94,.93,.92,.91,.9,.89], { hotSamples: 40 })); assert.ok(result.causes.some((cause) => cause.cause === "temperature")); assert.ok(!result.causes.some((cause) => cause.cause === "inverter_fault")); });
