"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import GlassCard from "@/components/dashboard/GlassCard";
import { useSettings } from "@/components/SettingsProvider";
import { diagnoseSolar, type DoctorDiagnostic, type DoctorSample } from "@/lib/solar-doctor";
import { applyRealtimeAdjustment, calculateForecast, isDaylightTime, mergeCurrentWeatherObservation, ORIENTATION_AZIMUTH, parsePowerKw, type ForecastHour, type SolarForecastSettings, type WeatherHour } from "@/lib/solar-forecast";
import type { LiveData } from "@/lib/knox";
import AnimatedAIIcon from "@/components/dashboard/AnimatedAIIcon";

const SETTINGS_KEY = "knox_solar_forecast_settings_v1";
const LEARNING_KEY = "knox_solar_forecast_learning_v1";
const SAMPLES_KEY = "knox_solar_doctor_samples_v1";
const CACHE_KEY = "knox_gemini_solar_doctor_v1";
const SAMPLE_INTERVAL = 5 * 60_000;
const CACHE_MS = 15 * 60_000;

interface WeatherResponse { current?: Record<string, number | string>; hourly?: Record<string, Array<number | string>>; daily?: { sunrise?: string[]; sunset?: string[] }; }
interface ForecastLearning { calibration?: number; cloudCoefficient?: number; temperatureCoefficient?: number; }
interface DoctorExplanation { headline: string; explanation: string; primaryCause: string; confidence: "high" | "medium" | "low"; recommendations: string[]; urgency: string; technicianRecommended: boolean; source: "gemini" | "local"; }

function readLocal<T>(key: string, fallback: T): T { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
function number(value: unknown): number | null { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : null; }
function parseWeather(data: WeatherResponse): WeatherHour[] {
  const hourly = data.hourly; if (!hourly?.time) return [];
  return hourly.time.map((time, index) => ({ time: String(time), temperature: Number(hourly.temperature_2m?.[index] ?? 25), humidity: Number(hourly.relative_humidity_2m?.[index] ?? 0), cloudCover: Number(hourly.cloud_cover?.[index] ?? 0), precipitationProbability: Number(hourly.precipitation_probability?.[index] ?? 0), windSpeed: Number(hourly.wind_speed_10m?.[index] ?? 0), uvIndex: Number(hourly.uv_index?.[index] ?? 0), weatherCode: Number(hourly.weather_code?.[index] ?? 0), irradiance: Number(hourly.shortwave_radiation?.[index] ?? 0), tiltedIrradiance: hourly.global_tilted_irradiance?.[index] == null ? null : Number(hourly.global_tilted_irradiance[index]) }));
}
function nearest(hours: ForecastHour[], now: number) { return hours.reduce<ForecastHour | null>((best, hour) => !best || Math.abs(new Date(hour.time).getTime() - now) < Math.abs(new Date(best.time).getTime() - now) ? hour : best, null); }
function localExplanation(diagnostic: DoctorDiagnostic, language: "ur" | "en"): DoctorExplanation {
  const ur = language === "ur"; const cause = diagnostic.causes[0]?.cause ?? "unknown";
  const names: Record<string, [string, string]> = { weather: ["Weather explains the drop", "موسم پیداوار میں کمی کی وضاحت کرتا ہے"], rain: ["Rain is reducing production", "بارش پیداوار کم کر رہی ہے"], normalClipping: ["Normal inverter limiting", "انورٹر کی معمول کی حد"], temperature: ["Heat is reducing efficiency", "گرمی کارکردگی کم کر رہی ہے"], inverter: ["Inverter evidence needs attention", "انورٹر کی صورتحال توجہ چاہتی ہے"], soiling: ["Panels may need inspection", "پینلز کو دیکھنے کی ضرورت ہو سکتی ہے"], shading: ["Shading is possible", "سایہ ممکن ہے"], unknown: ["More evidence is needed", "مزید معلومات درکار ہیں"] };
  const healthy = diagnostic.status === "healthy" || diagnostic.status === "normal_clipping";
  return { headline: healthy ? (ur ? "آپ کا سولر سسٹم صحت مند لگتا ہے۔" : "Your solar system looks healthy.") : ur ? "پیداوار پیشگوئی سے کم ہے۔" : "Production is below expected.", primaryCause: names[cause]?.[ur ? 1 : 0] ?? names.unknown[ur ? 1 : 0], explanation: diagnostic.status === "unavailable" ? (ur ? "سولر ڈاکٹر کو دن کی روشنی، موسم اور سولر سیٹ اپ درکار ہے۔" : "Solar Doctor needs daylight, weather, and solar setup data before it can compare production.") : !diagnostic.persistent && !healthy ? (ur ? "یہ فرق ابھی کافی دیر برقرار نہیں رہا، اس لیے اسے خرابی نہیں کہا جا رہا۔" : "The difference has not persisted long enough to call it a system issue.") : diagnostic.causes[0]?.evidence[0] ?? (ur ? "کوئی غیر معمولی نقصان نہیں ملا۔" : "No unusual production loss was detected."), confidence: diagnostic.persistent || healthy ? "high" : "low", recommendations: healthy ? [ur ? "معمول کے مطابق نگرانی جاری رکھیں۔" : "Continue normal monitoring."] : cause === "inverter" ? [ur ? "فالٹ کوڈ نوٹ کریں اور مستند سولر ٹیکنیشن سے رابطہ کریں۔" : "Note the fault code and contact a qualified solar technician."] : [ur ? "اگلی چند ریڈنگز کا انتظار کریں اور موسم سے موازنہ کریں۔" : "Monitor the next few readings and compare them with current weather."], urgency: cause === "inverter" ? "technician" : healthy ? "none" : "monitor", technicianRecommended: cause === "inverter", source: "local" };
}

export default function AISolarDoctor({ data }: { data: LiveData }) {
  const { language, dir } = useSettings();
  const [settings, setSettings] = useState<SolarForecastSettings | null>(null); const [weather, setWeather] = useState<WeatherResponse | null>(null); const [calibration, setCalibration] = useState(1); const [samples, setSamples] = useState<DoctorSample[]>([]); const [open, setOpen] = useState(false); const [ai, setAi] = useState<{ signature: string; value: DoctorExplanation } | null>(null); const [aiLoading, setAiLoading] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { const learning = readLocal<ForecastLearning>(LEARNING_KEY, {}); setSettings(readLocal<SolarForecastSettings | null>(SETTINGS_KEY, null)); setCalibration(Number(learning.calibration ?? 1) * Number(learning.cloudCoefficient ?? 1) * Number(learning.temperatureCoefficient ?? 1)); setSamples(readLocal<DoctorSample[]>(SAMPLES_KEY, [])); }, 0); return () => window.clearTimeout(timer); }, []);
  const fetchWeather = useCallback(async (config: SolarForecastSettings) => { const params = new URLSearchParams({ latitude: String(config.latitude), longitude: String(config.longitude), tilt: String(config.roofTilt), azimuth: String(ORIENTATION_AZIMUTH[config.orientation]) }); try { const response = await fetch(`/api/forecast/weather?${params}`, { cache: "no-store" }); if (response.ok) setWeather(await response.json() as WeatherResponse); } catch { /* deterministic unavailable state */ } }, []);
  useEffect(() => { if (!settings) return; const timer = window.setTimeout(() => void fetchWeather(settings), 0); const interval = window.setInterval(() => void fetchWeather(settings), 5 * 60_000); return () => { window.clearTimeout(timer); window.clearInterval(interval); }; }, [fetchWeather, settings]);

  const actualKw = parsePowerKw(data.pvPower.value, data.pvPower.unit);
  const now = new Date(data.fetchedAt).getTime();
  const current = useMemo(() => { if (!settings || !weather?.daily?.sunrise?.[0] || !weather.daily.sunset?.[0] || !isDaylightTime(now, weather.daily.sunrise[0], weather.daily.sunset[0])) return null; const observed = mergeCurrentWeatherObservation(parseWeather(weather), weather.current, data.fetchedAt); const baseForecast = calculateForecast(settings, observed, weather.daily.sunrise[0], weather.daily.sunset[0], calibration); return nearest(applyRealtimeAdjustment(baseForecast, data.fetchedAt, actualKw ?? 0), now); }, [actualKw, calibration, data.fetchedAt, now, settings, weather]);
  const currentRain = (number(weather?.current?.precipitation) ?? 0) > 0 || (number(weather?.current?.rain) ?? 0) > 0 || (number(weather?.current?.showers) ?? 0) > 0;
  const previousWeather = current && weather ? parseWeather(weather).filter((hour) => new Date(hour.time).getTime() < now).at(-1) : null;
  const diagnostic = diagnoseSolar({ now, expectedAcKw: current?.outputKw ?? null, actualAcKw: actualKw, panelCapacityKw: settings ? settings.panels * settings.panelWattage / 1000 : 0, inverterMaxAcKw: settings?.maxOutputKw ?? null, irradiance: number(weather?.current?.shortwave_radiation) ?? current?.irradiance ?? null, previousIrradiance: previousWeather?.irradiance ?? null, cloudCover: number(weather?.current?.cloud_cover) ?? current?.cloudCover ?? null, temperatureC: number(weather?.current?.temperature_2m) ?? current?.temperature ?? null, rain: currentRain, weatherCode: number(weather?.current?.weather_code) ?? current?.weatherCode ?? null, gridConnected: data.gridConnected, statusCode: data.statusCode, faultCode: number(data.faultCode.value) ?? 0, warningCode: number(data.warningCode.value) ?? 0, history: samples });

  useEffect(() => { if (!current || actualKw === null) return; const last = samples.at(-1); if (last && now - last.time < SAMPLE_INTERVAL) return; const next = [...samples, { time: now, expectedKw: current.outputKw, actualKw, irradiance: number(weather?.current?.shortwave_radiation) ?? current.irradiance, cloudCover: number(weather?.current?.cloud_cover) ?? current.cloudCover, rain: currentRain, temperatureC: number(weather?.current?.temperature_2m) ?? current.temperature, faultCode: number(data.faultCode.value) ?? 0, warningCode: number(data.warningCode.value) ?? 0, online: data.statusCode !== 1 }].filter((sample) => sample.time >= now - 90 * 86400000).slice(-26000); const timer = window.setTimeout(() => { localStorage.setItem(SAMPLES_KEY, JSON.stringify(next)); setSamples(next); }, 0); return () => window.clearTimeout(timer); }, [actualKw, current, currentRain, data.faultCode.value, data.statusCode, data.warningCode.value, now, samples, weather]);

  const signature = `${language}:${diagnostic.status}:${Math.round((diagnostic.performanceRatio ?? 0) * 10)}:${diagnostic.causes[0]?.cause ?? "none"}:${diagnostic.persistent}:${data.faultCode.value}:${data.warningCode.value}`;
  const fallback = localExplanation(diagnostic, language);
  const requestPayload = JSON.stringify({ language, system: settings ? { panelCapacityKw: settings.panels * settings.panelWattage / 1000, inverterMaxAcKw: settings.maxOutputKw ?? null, tilt: settings.roofTilt, orientation: settings.orientation, efficiencyPercent: settings.systemEfficiency } : {}, weather: current ? { irradiance: number(weather?.current?.shortwave_radiation) ?? current.irradiance, poaIrradiance: current.tiltedIrradiance, cloudCover: current.cloudCover, temperatureC: current.temperature, rain: currentRain, weatherCode: current.weatherCode } : {}, diagnostic });
  useEffect(() => { if (!open || diagnostic.status === "unavailable") return; let cancelled = false; try { const cached = readLocal<{ expiresAt: number; signature: string; value: DoctorExplanation } | null>(CACHE_KEY, null); if (cached && cached.expiresAt > Date.now() && cached.signature === signature) { const timer = window.setTimeout(() => setAi({ signature, value: cached.value }), 0); return () => { cancelled = true; window.clearTimeout(timer); }; } } catch { /* fresh request */ } const timer = window.setTimeout(async () => { setAiLoading(true); try { const response = await fetch("/api/ai/solar-doctor", { method: "POST", headers: { "Content-Type": "application/json" }, body: requestPayload }); if (!response.ok) return; const value = await response.json() as DoctorExplanation; if (!cancelled) { setAi({ signature, value }); localStorage.setItem(CACHE_KEY, JSON.stringify({ expiresAt: Date.now() + CACHE_MS, signature, value })); } } finally { if (!cancelled) setAiLoading(false); } }, 250); return () => { cancelled = true; window.clearTimeout(timer); }; }, [diagnostic.status, open, requestPayload, signature]);

  const explanation = ai?.signature === signature ? ai.value : fallback;
  const color = diagnostic.severity === "good" ? "text-emerald-300" : diagnostic.severity === "critical" ? "text-red-300" : diagnostic.severity === "warning" ? "text-amber-300" : "text-sky-300";
  return <>
    <GlassCard className="border-violet-400/15 bg-violet-400/[0.025]">
      <div className="flex items-start gap-4"><AnimatedAIIcon tone="sky" label={language === "ur" ? "اے آئی سولر ڈاکٹر" : "AI Solar Doctor"} /><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-violet-300">AI Solar Doctor</p><h2 className={`mt-2 text-lg font-semibold ${color}`}>{fallback.headline}</h2><p className="mt-1.5 text-sm leading-6 text-slate-400">{diagnostic.performanceRatio === null ? fallback.explanation : `${Math.round(diagnostic.performanceRatio * 100)}% ${language === "ur" ? "متوقع پیداوار" : "of expected production"} · ${fallback.primaryCause}`}</p></div><button type="button" onClick={() => setOpen(true)} className="shrink-0 rounded-xl border border-violet-300/15 bg-violet-300/[.07] px-3 py-2 text-xs font-semibold text-violet-200">{language === "ur" ? "تشخیص" : "View diagnosis"}</button></div>
    </GlassCard>
    {open && <div className="fixed inset-0 z-[90] flex items-end justify-center bg-[#03070d]/85 backdrop-blur-md sm:items-center sm:p-5" onMouseDown={() => setOpen(false)}><section dir={dir} role="dialog" aria-modal="true" aria-label="AI Solar Doctor" onMouseDown={(event) => event.stopPropagation()} className="max-h-[94dvh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] border border-white/[.08] bg-[#091019] p-5 shadow-2xl sm:rounded-[2rem] sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-300">🩺 AI Solar Doctor</p><h2 className={`mt-2 text-2xl font-bold ${color}`}>{explanation.headline}</h2></div><button type="button" onClick={() => setOpen(false)} className="h-9 w-9 rounded-xl border border-white/10 text-slate-400">×</button></div>
      <div className="mt-5 grid grid-cols-3 gap-2"><DoctorMetric label={language === "ur" ? "متوقع" : "Expected"} value={diagnostic.expectedAcKw === null ? "—" : `${diagnostic.expectedAcKw.toFixed(2)} kW`} /><DoctorMetric label={language === "ur" ? "اصل" : "Actual"} value={diagnostic.actualAcKw === null ? "—" : `${diagnostic.actualAcKw.toFixed(2)} kW`} /><DoctorMetric label={language === "ur" ? "فرق" : "Difference"} value={diagnostic.underperformancePercent === null ? "—" : `-${diagnostic.underperformancePercent.toFixed(0)}%`} /></div>
      <div className="mt-5 rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{language === "ur" ? "سب سے ممکنہ وجہ" : "Most likely cause"}</p><span className="text-[10px] text-violet-300">{aiLoading ? "Analyzing…" : explanation.source === "gemini" ? "Gemini explanation" : "Local analysis"}</span></div><h3 className="mt-2 text-lg font-semibold text-white">{explanation.primaryCause}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{explanation.explanation}</p></div>
      <h3 className="mt-6 text-sm font-semibold text-white">{language === "ur" ? "کیا چیک کریں" : "What to check"}</h3><ol className="mt-3 space-y-2">{explanation.recommendations.map((item, index) => <li key={item} className="flex gap-3 rounded-xl bg-white/[.025] p-3 text-sm text-slate-300"><span className="text-violet-300">{index + 1}</span>{item}</li>)}</ol>
      <h3 className="mt-6 text-sm font-semibold text-white">{language === "ur" ? "حالیہ ٹائم لائن" : "Recent timeline"}</h3><div className="mt-3 space-y-2">{samples.slice(-6).reverse().map((sample) => <div key={sample.time} className="grid grid-cols-[70px_1fr_1fr_24px] gap-2 text-xs text-slate-400"><span>{new Date(sample.time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span><span>{sample.expectedKw.toFixed(2)} kW exp.</span><span>{sample.actualKw.toFixed(2)} kW act.</span><span>{sample.actualKw >= sample.expectedKw * .8 ? "✓" : "⚠"}</span></div>)}{!samples.length && <p className="text-sm text-slate-500">{language === "ur" ? "پہلی تشخیصی ریڈنگ محفوظ کی جا رہی ہے۔" : "Collecting the first diagnostic reading."}</p>}</div>
      <p className="mt-6 border-t border-white/[.06] pt-4 text-[11px] leading-5 text-slate-600">{language === "ur" ? "یہ تشخیص تخمینہ ہے، یقینی ہارڈویئر تشخیص نہیں۔ بجلی کے آلات نہ کھولیں؛ فالٹ کی صورت میں مستند ٹیکنیشن سے رابطہ کریں۔" : "This is an evidence-based estimate, not a confirmed hardware diagnosis. Do not open electrical equipment; contact a qualified technician for active faults."}</p>
    </section></div>}
  </>;
}

function DoctorMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[.06] bg-black/10 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-sm font-semibold tabular-nums text-white">{value}</p></div>; }
