"use client";

import { useEffect, useMemo, useState } from "react";
import GlassCard from "@/components/dashboard/GlassCard";
import { useSettings } from "@/components/SettingsProvider";
import { aggregateDoctorSamples, analyzePredictiveHealth, detectHealthPatterns, type MaintenanceEvent, type MaintenanceType } from "@/lib/predictive-solar-health";
import type { DoctorSample } from "@/lib/solar-doctor";
import type { SolarForecastSettings } from "@/lib/solar-forecast";
import AnimatedAIIcon from "@/components/dashboard/AnimatedAIIcon";
import { notificationsGranted, showNotificationSafely } from "@/lib/browser-notifications";

const SAMPLES_KEY="knox_solar_doctor_samples_v1", MAINTENANCE_KEY="knox_solar_maintenance_v1", SETTINGS_KEY="knox_solar_forecast_settings_v1", CACHE_KEY="knox_predictive_health_ai_v1";
interface Explanation { headline:string; summary:string; primaryConcern:string; confidence:"low"|"medium"|"high"; recommendations:string[]; technicianRecommended:boolean; source:"gemini"|"local"; }
function read<T>(key:string,fallback:T):T{try{const value=localStorage.getItem(key);return value?JSON.parse(value) as T:fallback}catch{return fallback}}
function causeName(cause:string,ur:boolean){const names:Record<string,[string,string]>={weather:["Weather variation","موسم کی تبدیلی"],soiling:["Possible panel soiling","پینلز پر ممکنہ گندگی"],shading:["Possible recurring shading","ممکنہ مسلسل سایہ"],inverter_fault:["Inverter warning evidence","انورٹر کی تنبیہ"],inverter_degradation:["Possible system/inverter change","سسٹم یا انورٹر میں ممکنہ تبدیلی"],communication_issue:["Monitoring communication gaps","مانیٹرنگ رابطے میں وقفہ"],temperature:["High-temperature effect","زیادہ درجہ حرارت کا اثر"],sensor_issue:["Possible data inconsistency","ممکنہ ڈیٹا مسئلہ"],normal_variation:["Normal variation","معمول کی تبدیلی"],unknown:["More evidence needed","مزید معلومات درکار ہیں"]};return names[cause]?.[ur?1:0]??names.unknown[ur?1:0]}

export default function PredictiveSolarHealth(){
 const {language,dir}=useSettings();const ur=language==="ur";const [samples,setSamples]=useState<DoctorSample[]>([]);const [events,setEvents]=useState<MaintenanceEvent[]>([]);const [settings,setSettings]=useState<SolarForecastSettings|null>(null);const [open,setOpen]=useState(false);const [recording,setRecording]=useState(false);const [ai,setAi]=useState<{signature:string;value:Explanation}|null>(null);const [loading,setLoading]=useState(false);
 useEffect(()=>{const load=()=>{setSamples(read<DoctorSample[]>(SAMPLES_KEY,[]));setEvents(read<MaintenanceEvent[]>(MAINTENANCE_KEY,[]));setSettings(read<SolarForecastSettings|null>(SETTINGS_KEY,null))};const timer=window.setTimeout(load,0), interval=window.setInterval(load,5*60_000);return()=>{clearTimeout(timer);clearInterval(interval)}},[]);
 const days=useMemo(()=>aggregateDoctorSamples(samples),[samples]);const patterns=useMemo(()=>detectHealthPatterns(samples),[samples]);const health=useMemo(()=>analyzePredictiveHealth(days,events,patterns),[days,events,patterns]);
 useEffect(()=>{if(health.status!=="warning"&&health.status!=="critical")return;if(!notificationsGranted())return;const key=`knox_health_alert_${health.status}`;const previous=Number(localStorage.getItem(key)??0);if(Date.now()-previous<24*60*60_000)return;localStorage.setItem(key,String(Date.now()));void showNotificationSafely("Knox Solar Health",{body:health.status==="critical"?"A major persistent performance change needs attention.":"Weather-normalized solar performance is declining.",icon:"/icons/icon-192.png"})},[health.status]);
 const top=health.causes[0];const signature=`${language}:${health.status}:${Math.round(health.healthScore/5)*5}:${Math.round(health.slopePointsPerWeek)}:${top?.cause??"none"}:${events.at(-1)?.id??"none"}`;
 const local:Explanation={headline:health.status==="building_baseline"?(ur?"صحت کا بنیادی معیار بن رہا ہے":"Building your solar health baseline"):health.status==="insufficient_data"?(ur?"قابل اعتماد ڈیٹا کافی نہیں":"Not enough reliable data yet"):health.direction==="declining"?(ur?"کارکردگی میں ابتدائی کمی دیکھی گئی":"An early performance decline was detected"):(ur?"سولر کی کارکردگی مستحکم ہے":"Solar performance is stable"),summary:health.daysAvailable<7?(ur?`${health.daysAvailable} دن محفوظ ہیں۔ قابل اعتماد رجحان کے لیے کم از کم 7 دن درکار ہیں۔`:`${health.daysAvailable} recorded days are available. At least 7 reliable days are needed for an early trend.`):top?.evidence[0]??(ur?"موسم کے مطابق کارکردگی معمول کے اندر ہے۔":"Weather-normalized performance remains within its normal range."),primaryConcern:causeName(top?.cause??"unknown",ur),confidence:health.confidence,recommendations:health.status==="building_baseline"||health.status==="insufficient_data"?[ur?"ایپ کو دن کے وقت کھلا رکھیں تاکہ قابل اعتماد ریڈنگز جمع ہوں۔":"Keep monitoring during daylight so reliable samples can accumulate."]:top?.cause==="inverter_fault"?[ur?"فالٹ کوڈ نوٹ کریں؛ تنبیہ برقرار رہے تو مستند سولر ٹیکنیشن سے رابطہ کریں۔":"Note the fault code and contact a qualified solar technician if the warning persists."]:[ur?"رجحان کی نگرانی کریں اور صفائی یا مرمت کا واقعہ ریکارڈ کریں۔":"Keep monitoring the trend and record any cleaning or maintenance."],technicianRecommended:top?.cause==="inverter_fault",source:"local"};
 const payload=JSON.stringify({language,system:settings?{capacityKw:settings.panels*settings.panelWattage/1000,inverterKw:settings.maxOutputKw??null,panelCount:settings.panels,panelWattage:settings.panelWattage,tilt:settings.roofTilt,orientation:settings.orientation}:{},analysis:{status:health.status,healthScore:health.healthScore,risk:health.risk,dataQuality:Number(health.dataQuality.toFixed(2)),daysAvailable:health.daysAvailable,direction:health.direction,changePoints:Number(health.changePoints.toFixed(1)),slopePointsPerWeek:Number(health.slopePointsPerWeek.toFixed(1)),rolling7:health.rolling7===null?null:Number(health.rolling7.toFixed(2)),rolling14:health.rolling14===null?null:Number(health.rolling14.toFixed(2)),rolling30:health.rolling30===null?null:Number(health.rolling30.toFixed(2)),confidence:health.confidence,causes:health.causes.slice(0,4),patterns,maintenance:events.slice(-5)}});
 useEffect(()=>{if(!open)return;let cancelled=false;const cached=read<{expiresAt:number;signature:string;value:Explanation}|null>(CACHE_KEY,null);if(cached&&cached.expiresAt>Date.now()&&cached.signature===signature){const timer=setTimeout(()=>setAi({signature,value:cached.value}),0);return()=>{cancelled=true;clearTimeout(timer)}}const timer=setTimeout(async()=>{setLoading(true);try{const response=await fetch("/api/ai/predictive-health",{method:"POST",headers:{"Content-Type":"application/json"},body:payload});if(!response.ok)return;const value=await response.json() as Explanation;if(!cancelled){setAi({signature,value});localStorage.setItem(CACHE_KEY,JSON.stringify({expiresAt:Date.now()+15*60_000,signature,value}))}}finally{if(!cancelled)setLoading(false)}},300);return()=>{cancelled=true;clearTimeout(timer)}},[open,payload,signature]);
 const explanation=ai?.signature===signature?ai.value:local;const tone=health.status==="critical"?"text-red-300":health.status==="warning"||health.status==="early_warning"?"text-amber-300":"text-emerald-300";
 const addEvent=(type:MaintenanceType,time:number,id:string)=>{const next=[...events,{id,time,type}];localStorage.setItem(MAINTENANCE_KEY,JSON.stringify(next));setEvents(next);setRecording(false)};
 return <><GlassCard className="border-emerald-400/15 bg-emerald-400/[.025]"><div className="flex items-center gap-4"><AnimatedAIIcon tone="emerald" label={ur?"اے آئی پیشگوئی سولر صحت":"AI predictive solar health"}/><div className="min-w-0 flex-1"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-emerald-300">{ur?"اے آئی سولر صحت":"AI Solar Health"}</p><div className="mt-2 flex items-end gap-3"><strong className={`text-3xl ${tone}`}>{health.daysAvailable?health.healthScore:"—"}{health.daysAvailable?<span className="text-sm text-slate-600"> / 100</span>:null}</strong><span className="pb-1 text-xs text-slate-500">{health.status.replaceAll("_"," ")}</span></div><p className="mt-2 text-sm text-slate-400">{local.headline}{health.daysAvailable?` · ${health.daysAvailable} ${ur?"دن":"days"}`:""}</p></div><button type="button" onClick={()=>setOpen(true)} className="shrink-0 rounded-xl border border-emerald-300/15 bg-emerald-300/[.07] px-3 py-2 text-xs font-semibold text-emerald-200">{ur?"تجزیہ":"View analysis"}</button></div></GlassCard>
 {open&&<div className="fixed inset-0 z-[95] flex items-end justify-center bg-[#03070d]/85 backdrop-blur-md sm:items-center sm:p-5" onMouseDown={()=>setOpen(false)}><section dir={dir} role="dialog" aria-modal="true" onMouseDown={(e)=>e.stopPropagation()} className="max-h-[94dvh] w-full max-w-3xl overflow-y-auto rounded-t-[2rem] border border-white/[.08] bg-[#091019] p-5 sm:rounded-[2rem] sm:p-7"><div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-300">☀️ {ur?"پیشگوئی سولر صحت":"Predictive Solar Health"}</p><h2 className={`mt-2 text-2xl font-bold ${tone}`}>{explanation.headline}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{explanation.summary}</p></div><button type="button" onClick={()=>setOpen(false)} className="h-9 w-9 shrink-0 rounded-xl border border-white/10 text-slate-400">×</button></div>
 <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label={ur?"صحت":"Health"} value={`${health.healthScore}/100`}/><Metric label={ur?"ڈیٹا معیار":"Data quality"} value={`${Math.round(health.dataQuality*100)}%`}/><Metric label={ur?"رجحان":"Trend / week"} value={`${health.slopePointsPerWeek>0?"+":""}${health.slopePointsPerWeek.toFixed(1)} pt`}/><Metric label={ur?"خطرہ":"Risk"} value={health.risk}/></div>
 <div className="mt-5 rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex justify-between"><h3 className="text-sm font-semibold text-white">{ur?"کارکردگی کی ٹائم لائن":"Normalized performance timeline"}</h3><span className="text-[10px] text-violet-300">{loading?"Analyzing…":explanation.source==="gemini"?"Gemini explanation":"Local analysis"}</span></div><Timeline values={health.days.slice(-30).map((day)=>Math.round(day.ratio*100))}/></div>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/[.07] p-4"><h3 className="text-sm font-semibold text-white">{ur?"کیا بدلا؟":"What changed?"}</h3><div className="mt-3 space-y-2 text-sm text-slate-400"><Row label={ur?"ابتدائی معیار":"Historical baseline"} value={health.baselineRatio===null?"—":`${Math.round(health.baselineRatio*100)}%`}/><Row label={ur?"حالیہ":"Recent"} value={health.recentRatio===null?"—":`${Math.round(health.recentRatio*100)}%`}/><Row label={ur?"تبدیلی":"Change"} value={`${health.changePoints>0?"+":""}${health.changePoints.toFixed(1)} pt`}/></div></div><div className="rounded-2xl border border-white/[.07] p-4"><h3 className="text-sm font-semibold text-white">{ur?"ممکنہ وجوہات":"Possible explanations"}</h3><div className="mt-3 space-y-2">{health.causes.slice(0,3).map(c=><div key={c.cause} className="flex justify-between gap-3 text-sm"><span className="text-slate-400">{causeName(c.cause,ur)}</span><span className="text-slate-200">{c.score>=.7?"High":c.score>=.4?"Medium":"Low"}</span></div>)}</div></div></div>
 <div className="mt-5 rounded-2xl border border-violet-300/10 bg-violet-300/[.025] p-4"><h3 className="text-sm font-semibold text-white">{explanation.primaryConcern}</h3><ul className="mt-3 space-y-2">{explanation.recommendations.map(item=><li key={item} className="text-sm leading-6 text-slate-400">→ {item}</li>)}</ul></div>
 <div className="mt-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-white">{ur?"دیکھ بھال کی تاریخ":"Maintenance history"}</h3><button type="button" onClick={()=>setRecording(v=>!v)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300">+ {ur?"ریکارڈ":"Record maintenance"}</button></div>{recording&&<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{(["panels_cleaned","inverter_serviced","panels_replaced","wiring_serviced","shading_removed","other"] as MaintenanceType[]).map(type=><button key={type} type="button" onClick={()=>addEvent(type,Date.now(),crypto.randomUUID())} className="rounded-xl border border-white/[.08] p-3 text-xs text-slate-300">{type.replaceAll("_"," ")}</button>)}</div>}<div className="mt-3 space-y-2">{events.slice(-4).reverse().map(event=><div key={event.id} className="flex justify-between text-xs text-slate-500"><span>{event.type.replaceAll("_"," ")}</span><span>{new Date(event.time).toLocaleDateString()}</span></div>)}{!events.length&&<p className="text-xs text-slate-600">{ur?"ابھی کوئی دیکھ بھال ریکارڈ نہیں۔":"No maintenance recorded yet."}</p>}</div></div>
 <p className="mt-6 border-t border-white/[.06] pt-4 text-[11px] leading-5 text-slate-600">{ur?"یہ خطرے اور رجحان کا تخمینہ ہے، مستقبل کی خرابی کی یقینی پیشگوئی نہیں۔":"This estimates trends and risk; it does not predict a certain future failure. String, MPPT, battery, and curtailment telemetry are not available."}</p></section></div>}</>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.06] bg-black/10 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-sm font-semibold text-white">{value}</p></div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3"><span>{label}</span><strong className="text-slate-200">{value}</strong></div>}
function Timeline({values}:{values:number[]}){if(!values.length)return <p className="mt-4 text-sm text-slate-600">Collecting daily performance data.</p>;const points=values.map((value,index)=>`${values.length===1?50:index/(values.length-1)*100},${100-Math.max(0,Math.min(100,value))}`).join(" ");return <div className="mt-4"><svg viewBox="0 0 100 105" preserveAspectRatio="none" className="h-32 w-full" role="img" aria-label="Normalized solar performance trend"><path d="M0 5H100M0 25H100M0 50H100" stroke="rgba(255,255,255,.06)" strokeWidth=".5"/><polyline points={points} fill="none" stroke="#6ee7b7" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg><div className="flex justify-between text-[10px] text-slate-600"><span>{values.length} days ago</span><span>Today</span></div></div>}
