"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import type { LiveData } from "@/lib/knox";
import { healthScore, readLocal, ENERGY_HISTORY_KEY, APPLIANCES_KEY, type EnergyHistoryPoint } from "@/lib/energy-platform";
import {
  applyRealtimeAdjustment, calculateForecast, isDaylightTime, ORIENTATION_AZIMUTH, parsePowerKw,
  type Appliance, type ForecastHour, type SolarForecastSettings, type WeatherHour,
} from "@/lib/solar-forecast";
import type { DoctorSample } from "@/lib/solar-doctor";

const SETTINGS_KEY = "knox_solar_forecast_settings_v1", LEARNING_KEY = "knox_solar_forecast_learning_v1", SAMPLES_KEY = "knox_solar_doctor_samples_v1";
const LANGUAGE_KEY = "knox_voice_language_v1";
const NOOR_AVATAR = "/ai/shabnam-avatar.jpeg";
type VoiceLanguage = "auto" | "urdu" | "roman_urdu" | "english";
type AgentState = "idle" | "listening" | "thinking" | "speaking" | "error";
interface ForecastWeather { current?: Record<string, string | number>; hourly?: Record<string, Array<string | number>>; daily?: { sunrise?: string[]; sunset?: string[] }; }
interface Turn { user: string; assistant: string; time: number; }
interface Limits { maxSessions: number; maxSessionSeconds: number; maxSilenceSeconds: number; maxDailySeconds: number; }
interface GeneratedSpeech { data: string; sampleRate: number; mimeType: string; }

function weatherHours(weather: ForecastWeather): WeatherHour[] { const hourly=weather.hourly;if(!hourly?.time)return[];return hourly.time.map((time,i)=>({time:String(time),temperature:Number(hourly.temperature_2m?.[i]??25),humidity:Number(hourly.relative_humidity_2m?.[i]??0),cloudCover:Number(hourly.cloud_cover?.[i]??0),precipitationProbability:Number(hourly.precipitation_probability?.[i]??0),windSpeed:Number(hourly.wind_speed_10m?.[i]??0),uvIndex:Number(hourly.uv_index?.[i]??0),weatherCode:Number(hourly.weather_code?.[i]??0),irradiance:Number(hourly.shortwave_radiation?.[i]??0),tiltedIrradiance:hourly.global_tilted_irradiance?.[i]==null?null:Number(hourly.global_tilted_irradiance[i])})) }
function nearest(hours:ForecastHour[],now:number){return hours.reduce<ForecastHour|null>((best,hour)=>!best||Math.abs(new Date(hour.time).getTime()-now)<Math.abs(new Date(best.time).getTime()-now)?hour:best,null)}
function blobBase64(blob: Blob): Promise<string> { return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)}); }
function pcmBytes(value:string){const binary=window.atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i+=1)bytes[i]=binary.charCodeAt(i);return bytes}
function languageLabel(value:VoiceLanguage){return({auto:"Auto",urdu:"اردو",roman_urdu:"Roman Urdu",english:"English"} as const)[value]}

export default function UrduVoiceAssistant({ data }: { data: LiveData }) {
  const [open,setOpen]=useState(false),[state,setState]=useState<AgentState>("idle"),[message,setMessage]=useState("Tap to speak"),[turns,setTurns]=useState<Turn[]>([]);
  const [settings,setSettings]=useState<SolarForecastSettings|null>(null),[weather,setWeather]=useState<ForecastWeather|null>(null),[calibration,setCalibration]=useState(1);
  const [history,setHistory]=useState<EnergyHistoryPoint[]>([]),[samples,setSamples]=useState<DoctorSample[]>([]),[appliances,setAppliances]=useState<Appliance[]>([]);
  const [language,setLanguage]=useState<VoiceLanguage>("auto"),[limits,setLimits]=useState<Limits>({maxSessions:5,maxSessionSeconds:120,maxSilenceSeconds:30,maxDailySeconds:600});
  const sessionId=useRef(crypto.randomUUID()),sessionStarted=useRef(0),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),animation=useRef<number|null>(null),chunks=useRef<Blob[]>([]),playback=useRef<{source:AudioBufferSourceNode;context:AudioContext}|null>(null);

  useEffect(()=>{const timer=setTimeout(()=>{const learning=readLocal<{calibration?:number;cloudCoefficient?:number;temperatureCoefficient?:number}>(LEARNING_KEY,{});setSettings(readLocal<SolarForecastSettings|null>(SETTINGS_KEY,null));setCalibration(Number(learning.calibration??1)*Number(learning.cloudCoefficient??1)*Number(learning.temperatureCoefficient??1));setHistory(readLocal<EnergyHistoryPoint[]>(ENERGY_HISTORY_KEY,[]));setSamples(readLocal<DoctorSample[]>(SAMPLES_KEY,[]));setAppliances(readLocal<Appliance[]>(APPLIANCES_KEY,[]));setLanguage(readLocal<VoiceLanguage>(LANGUAGE_KEY,"auto"));void fetch("/api/ai/voice",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(value=>{if(value?.limits)setLimits(value.limits)}).catch(()=>{})},0);return()=>{clearTimeout(timer);window.speechSynthesis?.cancel();try{playback.current?.source.stop()}catch{}void playback.current?.context.close();stream.current?.getTracks().forEach(track=>track.stop());if(animation.current)cancelAnimationFrame(animation.current)}},[]);
  useEffect(()=>{if(!settings)return;const load=async()=>{const p=new URLSearchParams({latitude:String(settings.latitude),longitude:String(settings.longitude),tilt:String(settings.roofTilt),azimuth:String(ORIENTATION_AZIMUTH[settings.orientation])});try{const r=await fetch(`/api/forecast/weather?${p}`,{cache:"no-store"});if(r.ok)setWeather(await r.json() as ForecastWeather)}catch{}};const first=setTimeout(()=>void load(),0),interval=setInterval(()=>void load(),5*60_000);return()=>{clearTimeout(first);clearInterval(interval)}},[settings]);
  useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous}},[open]);

  const actualKw=parsePowerKw(data.pvPower.value,data.pvPower.unit)??0,loadKw=parsePowerKw(data.loadPower.value,data.loadPower.unit)??0,gridKw=parsePowerKw(data.gridPower.value,data.gridPower.unit);
  const forecasts=useMemo(()=>{if(!settings||!weather?.daily?.sunrise||!weather.daily.sunset)return{today:[],tomorrow:[],current:null};const hours=weatherHours(weather);const make=(i:number)=>weather.daily?.sunrise?.[i]&&weather.daily?.sunset?.[i]?calculateForecast(settings,hours,weather.daily.sunrise[i],weather.daily.sunset[i],calibration):[];const today=make(0),tomorrow=make(1),now=new Date(data.fetchedAt).getTime();const adjusted=applyRealtimeAdjustment(today,data.fetchedAt,actualKw);return{today:adjusted,tomorrow,current:weather.daily.sunrise[0]&&weather.daily.sunset[0]&&isDaylightTime(now,weather.daily.sunrise[0],weather.daily.sunset[0])?nearest(adjusted,now):null}},[actualKw,calibration,data.fetchedAt,settings,weather]);
  const context=useMemo(()=>{const todayEnergy=forecasts.today.reduce((sum,h)=>sum+h.outputKw,0),tomorrowEnergy=forecasts.tomorrow.reduce((sum,h)=>sum+h.outputKw,0);const best=[...forecasts.tomorrow].sort((a,b)=>b.outputKw-a.outputKw).slice(0,3).map(h=>new Date(h.time).toLocaleTimeString("en-PK",{hour:"numeric"}));const health=healthScore(data,history);const lastSample=samples.at(-1);return{current:{solarKw:actualKw,loadKw,gridKw,gridConnected:data.gridConnected,todayEnergyKwh:Number(data.todayEnergy.value),expectedSolarKw:forecasts.current?.outputKw,timestamp:data.fetchedAt,statusText:data.statusText,faultCode:Number(data.faultCode.value),warningCode:Number(data.warningCode.value)},forecast:{todayEnergyKwh:todayEnergy||null,tomorrowEnergyKwh:tomorrowEnergy||null,todayPeakKw:Math.max(0,...forecasts.today.map(h=>h.outputKw)),tomorrowPeakKw:Math.max(0,...forecasts.tomorrow.map(h=>h.outputKw)),bestHours:best},weather:{current:weather?.current??null,today:forecasts.today.length?{averageCloudPercent:forecasts.today.reduce((s,h)=>s+h.cloudCover,0)/forecasts.today.length}:null,tomorrow:forecasts.tomorrow.length?{averageCloudPercent:forecasts.tomorrow.reduce((s,h)=>s+h.cloudCover,0)/forecasts.tomorrow.length}:null},health,doctor:lastSample?{expectedKw:lastSample.expectedKw,actualKw:lastSample.actualKw,performingNormally:lastSample.actualKw>=lastSample.expectedKw*.8,faultCode:lastSample.faultCode??0,warningCode:lastSample.warningCode??0}:{available:false,message:"Data unavailable."},appliances:appliances.length?{configured:appliances.map(a=>({name:a.name,watts:a.watts,quantity:a.quantity})),recommendedSolarHours:best}:{available:false,message:"Data unavailable."},system:settings?{panels:settings.panels,panelWattage:settings.panelWattage,orientation:settings.orientation,roofTilt:settings.roofTilt,maxOutputKw:settings.maxOutputKw??null}:{available:false,message:"Data unavailable."},history:history.slice(-24),voiceLanguage:language}},[actualKw,appliances,data,forecasts,gridKw,history,language,loadKw,samples,settings,weather]);

  const stopPlayback=useCallback(()=>{window.speechSynthesis.cancel();const active=playback.current;playback.current=null;if(active){try{active.source.stop()}catch{}void active.context.close()}},[]);
  const speak=useCallback((answer:string,responseLanguage:string,speech:GeneratedSpeech|null)=>{stopPlayback();setState("speaking");setMessage("Speaking… tap the mic to interrupt");if(speech?.data){try{const bytes=pcmBytes(speech.data),audioContext=new AudioContext(),buffer=audioContext.createBuffer(1,Math.floor(bytes.byteLength/2),speech.sampleRate),channel=buffer.getChannelData(0),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);for(let i=0;i<channel.length;i+=1)channel[i]=view.getInt16(i*2,true)/32768;const source=audioContext.createBufferSource();source.buffer=buffer;source.connect(audioContext.destination);playback.current={source,context:audioContext};source.onended=()=>{if(playback.current?.source!==source)return;playback.current=null;void audioContext.close();setState("idle");setMessage("Tap to ask another question")};source.start();return}catch{stopPlayback()}}const utterance=new SpeechSynthesisUtterance(answer),voices=window.speechSynthesis.getVoices(),ur=responseLanguage==="urdu"||responseLanguage==="mixed";utterance.lang=ur?"ur-PK":"en-PK";utterance.voice=voices.find(v=>v.lang.toLowerCase()===(ur?"ur-pk":"en-pk"))??voices.find(v=>v.lang.toLowerCase().startsWith(ur?"ur":"en"))??null;utterance.rate=ur?.9:.95;utterance.onend=()=>{setState("idle");setMessage("Tap to ask another question")};utterance.onerror=()=>{setState("error");setMessage("Audio playback failed")};window.speechSynthesis.speak(utterance)},[stopPlayback]);
  const ask=useCallback(async(audio:Blob|null,durationSeconds:number,query?:string)=>{setState("thinking");setMessage("Checking your solar data…");try{const encoded=audio?await blobBase64(audio):undefined;const response=await fetch("/api/ai/voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:sessionId.current,durationSeconds,audio:encoded,mimeType:audio?.type,query,language,context,history:turns.map(t=>({user:t.user,assistant:t.assistant}))})});const result=await response.json() as {transcript?:string;response?:string;language?:string;error?:string};if(!response.ok||!result.response){setState("error");setMessage(result.error??"Voice assistant is temporarily unavailable. Please try again.");return}const responseLanguage=result.language??"mixed",turn={user:result.transcript??query??"",assistant:result.response,time:Date.now()};setTurns(previous=>[...previous,turn].slice(-8));setState("speaking");setMessage("Preparing Noor’s voice…");const voiceResponse=await fetch("/api/ai/voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"synthesize",transcript:result.response,language:responseLanguage})});const voiceResult=await voiceResponse.json().catch(()=>null) as {speech?:GeneratedSpeech}|null;speak(result.response,responseLanguage,voiceResponse.ok?voiceResult?.speech??null:null)}catch{setState("error");setMessage("Network failure. Please try again.")}},[context,language,speak,turns]);
  const stopRecording=useCallback(()=>{if(animation.current){cancelAnimationFrame(animation.current);animation.current=null}if(recorder.current?.state==="recording")recorder.current.stop()},[]);
  const startListening=useCallback(async()=>{if(state==="speaking")window.speechSynthesis.cancel();if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setState("error");setMessage("Microphone is unavailable in this browser.");return}try{const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});stream.current=media;chunks.current=[];const preferred=MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":MediaRecorder.isTypeSupported("audio/mp4")?"audio/mp4":"";const rec=new MediaRecorder(media,preferred?{mimeType:preferred}:undefined);recorder.current=rec;sessionStarted.current=sessionStarted.current||Date.now();const utteranceStarted=Date.now();let lastSound=Date.now(),heardSpeech=false;rec.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};rec.onstop=()=>{media.getTracks().forEach(track=>track.stop());stream.current=null;const duration=(Date.now()-utteranceStarted)/1000,blob=new Blob(chunks.current,{type:rec.mimeType});if(blob.size<200){setState("idle");setMessage("I couldn’t hear anything. Tap to try again.");return}void ask(blob,duration)};rec.start(250);setState("listening");setMessage("I’m listening…");const audioContext=new AudioContext(),source=audioContext.createMediaStreamSource(media),analyser=audioContext.createAnalyser(),values=new Uint8Array(analyser.fftSize);source.connect(analyser);const monitor=()=>{analyser.getByteTimeDomainData(values);let peak=0;for(const value of values)peak=Math.max(peak,Math.abs(value-128));if(peak>8){heardSpeech=true;lastSound=Date.now()}const sessionElapsed=(Date.now()-sessionStarted.current)/1000;if(sessionElapsed>=limits.maxSessionSeconds||(heardSpeech&&(Date.now()-lastSound)/1000>=limits.maxSilenceSeconds)){void audioContext.close();stopRecording();return}animation.current=requestAnimationFrame(monitor)};monitor()}catch(error){setState("error");setMessage(error instanceof DOMException&&error.name==="NotAllowedError"?"Microphone access is required to use the voice assistant.":"Microphone is unavailable. Please try again.")}},[ask,limits.maxSessionSeconds,limits.maxSilenceSeconds,state,stopRecording]);
  const mic=()=>{if(state==="listening")stopRecording();else if(state!=="thinking"){if(state==="speaking")stopPlayback();void startListening()}};
  const closeNoor=()=>{stopPlayback();stopRecording();setOpen(false)};
  const changeLanguage=(value:VoiceLanguage)=>{setLanguage(value);localStorage.setItem(LANGUAGE_KEY,JSON.stringify(value))};
  const quickAsk=(query:string)=>{if(state!=="thinking"&&state!=="listening")void ask(null,0,query)};
  const stateLabel=state==="listening"?"Listening":state==="thinking"?"Thinking":state==="speaking"?"Speaking":state==="error"?"Needs attention":"Online";

  return <>
    <button type="button" onClick={()=>setOpen(true)} className="group fixed bottom-5 end-4 z-40 flex items-center gap-2.5 rounded-full border border-violet-300/30 bg-[#111827]/95 p-1.5 pe-1.5 shadow-2xl shadow-violet-950/60 backdrop-blur-xl transition hover:-translate-y-1 hover:border-violet-300/50 sm:bottom-7 sm:end-7 sm:pe-4" aria-label="Talk to Noor, AI Energy Agent">
      <span className="relative h-14 w-14 shrink-0"><span className="relative block h-full w-full overflow-hidden rounded-full ring-2 ring-violet-300/40"><Image src={NOOR_AVATAR} alt="Noor, AI Energy Agent" fill sizes="56px" className="object-cover object-[center_20%] transition group-hover:scale-105"/></span><span className="absolute -bottom-0.5 -end-0.5 z-10 h-4 w-4 rounded-full border-[3px] border-[#111827] bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,.75)]" aria-label="Noor is online"/></span>
      <span className="hidden text-start sm:block"><span className="block text-sm font-semibold text-white">Ask Noor</span><span className="block text-[10px] text-slate-500">Your solar assistant</span></span>
    </button>
    {open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#02050a]/90 p-0 backdrop-blur-xl sm:p-5" onMouseDown={closeNoor}>
      <section dir="ltr" role="dialog" aria-modal="true" aria-label="Noor AI Energy Agent" onMouseDown={e=>e.stopPropagation()} className="relative flex h-dvh w-full max-w-xl flex-col overflow-hidden border border-white/[.09] bg-[#080e17] shadow-2xl shadow-black/70 sm:h-[min(90dvh,760px)] sm:rounded-[2rem]">
        <div className="pointer-events-none absolute inset-x-0 top-0 h-64 bg-[radial-gradient(circle_at_50%_0%,rgba(139,92,246,.22),transparent_68%)]"/>
        <div className="relative flex items-center justify-between border-b border-white/[.06] px-5 py-4 sm:px-6">
          <div className="flex items-center gap-3"><div className="relative h-11 w-11 overflow-hidden rounded-full ring-1 ring-violet-300/40"><Image src={NOOR_AVATAR} alt="" fill sizes="44px" className="object-cover object-[center_20%]"/></div><div><div className="flex items-center gap-2"><h2 className="font-semibold text-white">Noor</h2><span className={`h-1.5 w-1.5 rounded-full ${state==="error"?"bg-red-400":"bg-emerald-400"}`}/></div><p className="text-[10px] font-medium uppercase tracking-[.16em] text-violet-300">AI Energy Agent · {stateLabel}</p></div></div>
          <button type="button" onClick={closeNoor} className="flex h-9 w-9 items-center justify-center rounded-full border border-white/[.08] bg-white/[.03] text-lg text-slate-400 transition hover:bg-white/[.07] hover:text-white" aria-label="Close Noor">×</button>
        </div>

        <div className="relative min-h-0 flex-1 overflow-y-auto px-5 pb-[calc(1.25rem+var(--safe-bottom))] sm:px-7 sm:pb-7">
          <div className="flex flex-col items-center pb-6 pt-8">
            <div className={`noor-orbit relative flex h-36 w-36 items-center justify-center rounded-full ${state==="listening"||state==="speaking"?"is-active":""}`}>
              <div className="absolute inset-3 overflow-hidden rounded-full border border-violet-300/25 shadow-[0_0_55px_rgba(139,92,246,.22)]"><Image src={NOOR_AVATAR} alt="Noor" fill sizes="120px" className="object-cover object-[center_20%]"/></div>
              {(state==="listening"||state==="speaking")&&<div className="absolute -bottom-2 flex h-8 items-center gap-1 rounded-full border border-white/10 bg-[#0b1220]/95 px-3 shadow-xl">{[10,18,25,15,28,20,12].map((height,index)=><span key={index} className="noor-wave w-0.5 rounded-full bg-violet-300" style={{height,animationDelay:`${index*80}ms`}}/>)}</div>}
              {state==="thinking"&&<span className="absolute -bottom-2 h-8 w-8 animate-spin rounded-full border-2 border-violet-300/20 border-t-violet-300 bg-[#0b1220]"/>}
            </div>
            <h3 className="mt-6 text-xl font-semibold text-white">{state==="idle"?"What would you like to know?":state==="listening"?"Go ahead, I’m listening":state==="thinking"?"Let me check that":state==="speaking"?"Here’s what I found":"Something needs attention"}</h3>
            <p className={`mt-2 min-h-5 text-center text-sm ${state==="error"?"text-red-300":"text-slate-400"}`}>{message}</p>
            <button type="button" onClick={mic} disabled={state==="thinking"} className={`mt-5 flex h-16 items-center gap-3 rounded-full border px-6 font-semibold text-white shadow-xl transition active:scale-95 disabled:opacity-50 ${state==="listening"?"border-red-300/40 bg-red-500 shadow-red-950/40":state==="speaking"?"border-sky-300/30 bg-sky-500 shadow-sky-950/40":"border-violet-300/30 bg-violet-500 shadow-violet-950/50 hover:bg-violet-400"}`}>{state==="speaking"?<span className="text-xl">■</span>:<MicIcon/>}<span>{state==="listening"?"Done speaking":state==="speaking"?"Interrupt Noor":"Tap to speak"}</span></button>
          </div>

          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
            <QuickPrompt icon="☀️" label="Morning briefing" onClick={()=>quickAsk("Give me my morning energy briefing using only available tool data.")} disabled={state==="thinking"||state==="listening"}/>
            <QuickPrompt icon="⚡" label="Solar now" onClick={()=>quickAsk("How much solar am I generating right now?")} disabled={state==="thinking"||state==="listening"}/>
            <QuickPrompt icon="📈" label="Today’s forecast" onClick={()=>quickAsk("How much solar will I generate today?")} disabled={state==="thinking"||state==="listening"}/>
            <QuickPrompt icon="🩺" label="System health" onClick={()=>quickAsk("Is my solar system healthy?")} disabled={state==="thinking"||state==="listening"}/>
          </div>

          {turns.length>0&&<div className="mt-6 border-t border-white/[.06] pt-5"><div className="mb-4 flex items-center justify-between"><h3 className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Conversation</h3><button type="button" onClick={()=>setTurns([])} className="text-[10px] text-slate-600 hover:text-slate-400">Clear</button></div><div className="space-y-4">{turns.slice(-4).map(turn=><div key={turn.time} className="space-y-2 text-sm"><div className="ms-auto max-w-[85%] rounded-2xl rounded-br-md bg-violet-500/15 px-4 py-3 text-slate-200">{turn.user}</div><div className="flex items-start gap-2.5"><div className="relative mt-0.5 h-7 w-7 shrink-0 overflow-hidden rounded-full"><Image src={NOOR_AVATAR} alt="" fill sizes="28px" className="object-cover object-[center_20%]"/></div><div className="max-w-[85%] rounded-2xl rounded-tl-md border border-white/[.06] bg-white/[.035] px-4 py-3 leading-6 text-slate-300">{turn.assistant}</div></div></div>)}</div></div>}

          <div className="mt-6 flex items-center justify-between rounded-2xl border border-white/[.06] bg-white/[.02] p-3"><div><p className="text-xs font-medium text-slate-300">Voice language</p><p className="mt-0.5 text-[10px] text-slate-600">Noor detects it automatically</p></div><select value={language} onChange={e=>changeLanguage(e.target.value as VoiceLanguage)} className="rounded-xl border border-white/10 bg-[#111923] px-3 py-2 text-xs text-slate-200">{(["auto","urdu","roman_urdu","english"] as VoiceLanguage[]).map(value=><option key={value} value={value}>{languageLabel(value)}</option>)}</select></div>
          <p className="mt-4 text-center text-[10px] leading-4 text-slate-600">🔒 Read-only · Audio is not stored · {limits.maxSessions} sessions/day · {limits.maxSessionSeconds}s/session</p>
        </div>
      </section>
    </div>}
  </>;
}
function MicIcon(){return <svg width="29" height="29" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0014 0M12 18v3M8 21h8"/></svg>}
function QuickPrompt({icon,label,onClick,disabled}:{icon:string;label:string;onClick:()=>void;disabled:boolean}){return <button type="button" onClick={onClick} disabled={disabled} className="group rounded-2xl border border-white/[.06] bg-white/[.025] p-3 text-start transition hover:border-violet-300/20 hover:bg-violet-300/[.06] disabled:opacity-40"><span className="text-lg">{icon}</span><span className="mt-2 block text-[11px] font-medium leading-4 text-slate-400 group-hover:text-slate-200">{label}</span></button>}
