"use client";

import { useEffect, useState } from "react";
import { useSettings } from "./SettingsProvider";
import { DEFAULT_RULES, ENERGY_RULES_KEY, readLocal, type NotificationRules } from "@/lib/energy-platform";
import { requestNotificationAccess } from "@/lib/browser-notifications";

export default function EnergyPlatformModal({ onClose }: { onClose: () => void }) {
  const { language, dir } = useSettings();
  const ur = language === "ur";
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", key); return () => { document.body.style.overflow = old; window.removeEventListener("keydown", key); }; }, [onClose]);
  return <div className="app-overlay fixed inset-0 z-[90] flex items-center justify-center bg-[#03070d]/80 backdrop-blur-md sm:p-5" onMouseDown={onClose}><div dir={dir} className="flex h-dvh w-full max-w-3xl flex-col overflow-hidden border border-white/[0.08] bg-[#091019] shadow-2xl sm:h-[min(86dvh,760px)] sm:rounded-[2rem]" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><header className="flex shrink-0 items-center justify-between border-b border-white/[0.07] px-5 py-4 sm:px-7"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-emerald-400">Knox Solar</p><h2 className="mt-1 text-xl font-semibold text-white">{ur ? "اطلاعات" : "Notification Center"}</h2></div><button onClick={onClose} className="icon-button" aria-label="Close">×</button></header><main className="flex-1 overflow-y-auto p-4 pb-[calc(2rem+var(--safe-bottom))] sm:p-7"><Alerts language={language}/></main></div></div>;
}

function Alerts({language}:{language:"ur"|"en"}) {const ur=language==="ur";const [rules,setRules]=useState<NotificationRules>(()=>({...DEFAULT_RULES,...readLocal(ENERGY_RULES_KEY,DEFAULT_RULES)}));const [message,setMessage]=useState<string|null>(null);const save=(next:NotificationRules)=>{setRules(next);localStorage.setItem(ENERGY_RULES_KEY,JSON.stringify(next));};const enable=async()=>{setMessage(null);const result=await requestNotificationAccess();if(result==="granted"){save({...rules,enabled:true});setMessage(ur?"اطلاعات کامیابی سے فعال ہو گئیں۔":"Notifications are enabled.");return}save({...rules,enabled:false});setMessage(result==="unsupported"?(ur?"یہ موبائل براؤزر اطلاعات کی حمایت نہیں کرتا۔ ایپ کو ہوم اسکرین پر انسٹال کر کے دوبارہ کوشش کریں۔":"This mobile browser does not support notifications. Install the app to your Home Screen and try again."):result==="denied"?(ur?"اطلاعات کی اجازت بند ہے۔ فون کی ترتیبات میں Knox Solar کو اجازت دیں۔":"Notification permission is blocked. Allow Knox Solar in your phone settings."):(ur?"اطلاعات فعال نہیں ہو سکیں، لیکن ایپ محفوظ طریقے سے چلتی رہے گی۔":"Notifications could not be enabled, but the app will continue working."))};return <Section title={ur?"سمارٹ اطلاعات":"Smart notifications"} hint={ur?"براؤزر اجازت کے بعد مقامی اطلاعات۔":"Local browser alerts after permission is granted."}>{message&&<p className="mb-3 rounded-xl border border-white/[.08] bg-white/[.03] p-3 text-sm text-slate-300">{message}</p>}<Toggle label={ur?"اطلاعات فعال":"Enable notifications"} value={rules.enabled} onChange={value=>value?void enable():save({...rules,enabled:false})}/><Rule label={ur?"سولر اس سے زیادہ ہو":"Solar exceeds"} value={rules.solarAboveKw} onChange={value=>save({...rules,solarAboveKw:value})}/><Rule label={ur?"اضافی سولر اس سے زیادہ ہو":"Surplus exceeds"} value={rules.surplusAboveKw} onChange={value=>save({...rules,surplusAboveKw:value})}/><Rule label={ur?"اچانک کمی فیصد":"Sudden production drop"} value={rules.suddenDropPercent} suffix="%" onChange={value=>save({...rules,suddenDropPercent:value})}/><Toggle label={ur?"آلہ محفوظ طریقے سے چل سکے":"An appliance can safely run"} value={rules.applianceReady} onChange={value=>save({...rules,applianceReady:value})}/><Toggle label={ur?"بادل آنے سے پہلے":"Before clouds arrive"} value={rules.cloudsAhead} onChange={value=>save({...rules,cloudsAhead:value})}/><Toggle label={ur?"انورٹر منقطع ہو":"Inverter disconnects"} value={rules.inverterOffline} onChange={value=>save({...rules,inverterOffline:value})}/></Section>}

function Section({title,hint,children}:{title:string;hint:string;children:React.ReactNode}){return <section><h3 className="text-2xl font-semibold text-white">{title}</h3><p className="mt-2 text-sm text-slate-500">{hint}</p><div className="mt-6">{children}</div></section>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="mb-2 flex items-center justify-between rounded-2xl border border-white/[.07] p-4 text-sm text-slate-300"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)} className="h-5 w-5 accent-emerald-400"/></label>}
function Rule({label,value,onChange,suffix="kW"}:{label:string;value:number;onChange:(v:number)=>void;suffix?:string}){return <label className="mb-2 flex items-center justify-between gap-4 rounded-2xl border border-white/[.07] p-4 text-sm text-slate-300"><span>{label}</span><span className="flex items-center gap-2"><input type="number" step=".1" value={value} onChange={e=>onChange(Number(e.target.value))} className="w-20 rounded-lg bg-black/20 p-2 text-end text-white outline-none"/>{suffix}</span></label>}
