"use client";

import { useEffect, useState } from "react";
import { useSettings } from "./SettingsProvider";
import { APPLIANCES_KEY, DEFAULT_RULES, ENERGY_HISTORY_KEY, ENERGY_RULES_KEY, ENERGY_SITES_KEY, FORECAST_SETTINGS_KEY, aggregateHistory, healthScore, historyCsv, readLocal, type EnergyHistoryPoint, type EnergySite, type NotificationRules } from "@/lib/energy-platform";
import { calculateForecast, DEFAULT_APPLIANCES, ORIENTATION_AZIMUTH, parsePowerKw, type Appliance, type ForecastHour, type SolarForecastSettings, type WeatherHour } from "@/lib/solar-forecast";
import type { LiveData } from "@/lib/knox";
import { applianceNames } from "@/lib/i18n/forecast";

type Tab = "appliances" | "schedule" | "analytics" | "alerts" | "sites" | "health";

export default function EnergyPlatformModal({ data, onClose }: { data: LiveData; onClose: () => void }) {
  const { language, dir } = useSettings();
  const ur = language === "ur";
  const [tab, setTab] = useState<Tab>("appliances");
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", key); return () => { document.body.style.overflow = old; window.removeEventListener("keydown", key); }; }, [onClose]);
  const tabs: Array<[Tab, string]> = [["appliances", ur ? "لوڈ سمیولیٹر" : "Load simulator"], ["schedule", ur ? "شیڈول" : "Scheduler"], ["analytics", ur ? "تجزیات" : "Analytics"], ["health", ur ? "صحت" : "Health"], ["alerts", ur ? "اطلاعات" : "Notifications"], ["sites", ur ? "مقامات" : "Sites"]];
  return <div className="app-overlay fixed inset-0 z-[90] flex items-center justify-center bg-[#03070d]/80 backdrop-blur-md sm:p-5" onMouseDown={onClose}><div dir={dir} className="flex h-dvh w-full max-w-4xl flex-col overflow-hidden border border-white/[0.08] bg-[#091019] shadow-2xl sm:h-[min(92dvh,880px)] sm:rounded-[2rem]" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><header className="flex shrink-0 items-center justify-between border-b border-white/[0.07] px-5 py-4 sm:px-7"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-emerald-400">Knox Intelligence</p><h2 className="mt-1 text-xl font-semibold text-white">{ur ? "توانائی مرکز" : "Energy Center"}</h2></div><button onClick={onClose} className="icon-button" aria-label="Close">×</button></header><nav className="hide-scrollbar flex shrink-0 gap-2 overflow-x-auto border-b border-white/[0.07] px-4 py-3 sm:px-7">{tabs.map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${tab === id ? "bg-emerald-300 text-[#062017]" : "bg-white/[0.04] text-slate-500"}`}>{label}</button>)}</nav><main className="flex-1 overflow-y-auto p-4 pb-[calc(2rem+var(--safe-bottom))] sm:p-7">{tab === "appliances" && <LoadSimulator data={data} language={language}/>} {tab === "schedule" && <Scheduler language={language}/>} {tab === "analytics" && <Analytics language={language}/>} {tab === "health" && <Health data={data} language={language}/>} {tab === "alerts" && <Alerts language={language}/>} {tab === "sites" && <Sites language={language}/>}</main></div></div>;
}

function LoadSimulator({ data, language }: { data: LiveData; language: "ur" | "en" }) {
  const ur = language === "ur"; const [items, setItems] = useState<Appliance[]>(() => readLocal(APPLIANCES_KEY, DEFAULT_APPLIANCES)); const [selected, setSelected] = useState<Record<string, number>>({}); const [marginPercent,setMarginPercent]=useState(()=>readLocal("knox_safety_margin_v1",15));
  const solar = parsePowerKw(data.pvPower.value, data.pvPower.unit) ?? 0; const current = parsePowerKw(data.loadPower.value, data.loadPower.unit) ?? 0; const extra = items.reduce((sum,item) => sum + (selected[item.id] ?? 0) * item.watts / 1000, 0); const margin = solar * marginPercent / 100; const remaining = solar - current - extra - margin; const safe = remaining >= 0;
  const selectedItems = items.filter(item => (selected[item.id] ?? 0) > 0).sort((a,b)=>b.watts-a.watts); const turnOff = selectedItems.find(item => item.watts / 1000 >= Math.abs(remaining)) ?? selectedItems[0];
  return <Section title={ur ? "سمارٹ لوڈ سمیولیٹر" : "Smart load simulator"} hint={ur ? "آلات منتخب کریں، حساب خود ہوگا۔" : "Select appliances; Knox calculates the result."}><div className="grid gap-3 sm:grid-cols-4"><Stat label={ur?"موجودہ لوڈ":"Current load"} value={`${current.toFixed(2)} kW`}/><Stat label={ur?"سولر":"Available solar"} value={`${solar.toFixed(2)} kW`}/><Stat label={ur?"حفاظتی گنجائش":"Safety margin"} value={`${margin.toFixed(2)} kW`}/><Stat label={ur?"باقی":"Remaining"} value={`${remaining.toFixed(2)} kW`} tone={safe?"good":"bad"}/></div><label className="mt-4 block rounded-2xl border border-white/[.07] bg-white/[.02] p-4"><span className="flex items-center justify-between text-xs text-slate-400"><span>{ur?"حفاظتی ریزرو":"Safety reserve"}</span><strong className="text-emerald-300">{marginPercent}%</strong></span><input type="range" min="5" max="30" step="5" value={marginPercent} onChange={event=>{const value=Number(event.target.value);setMarginPercent(value);localStorage.setItem("knox_safety_margin_v1",JSON.stringify(value));}} className="mt-3 w-full accent-emerald-400"/></label><div className={`mt-4 rounded-2xl border p-4 ${safe?"border-emerald-400/20 bg-emerald-400/[.07] text-emerald-300":"border-red-400/20 bg-red-400/[.07] text-red-300"}`}><strong>{safe ? (ur?"محفوظ":"SAFE") : (ur?"تجویز نہیں کیا جاتا":"NOT RECOMMENDED")}</strong>{!safe && turnOff && <p className="mt-1 text-sm">{ur?"بند کریں:":"Turn off:"} {applianceNames[language][turnOff.id] ?? turnOff.name}</p>}</div><div className="mt-5 grid gap-2 sm:grid-cols-2">{items.map((item,index)=><div key={item.id} className="flex items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-200">{applianceNames[language][item.id] ?? item.name}</p><div className="mt-1 flex items-center gap-2"><input value={item.watts} onChange={e=>{const next=items.map((x,i)=>i===index?{...x,watts:Number(e.target.value)}:x);setItems(next);localStorage.setItem(APPLIANCES_KEY,JSON.stringify(next));}} type="number" className="w-20 bg-transparent text-xs text-slate-500 outline-none"/><span className="text-xs text-slate-600">W</span></div></div><div className="flex items-center gap-2"><button onClick={()=>setSelected({...selected,[item.id]:Math.max(0,(selected[item.id]??0)-1)})} className="icon-button !h-8 !w-8">−</button><span className="w-5 text-center text-sm text-white">{selected[item.id]??0}</span><button onClick={()=>setSelected({...selected,[item.id]:(selected[item.id]??0)+1})} className="icon-button !h-8 !w-8">+</button></div></div>)}</div></Section>;
}

function apiWeatherHours(hourly: Record<string, Array<string|number>>): WeatherHour[] { return (hourly.time??[]).map((time,index)=>({time:String(time),temperature:Number(hourly.temperature_2m?.[index]??25),humidity:Number(hourly.relative_humidity_2m?.[index]??0),cloudCover:Number(hourly.cloud_cover?.[index]??0),precipitationProbability:Number(hourly.precipitation_probability?.[index]??0),windSpeed:Number(hourly.wind_speed_10m?.[index]??0),uvIndex:Number(hourly.uv_index?.[index]??0),weatherCode:Number(hourly.weather_code?.[index]??0),irradiance:Number(hourly.shortwave_radiation?.[index]??0),tiltedIrradiance:hourly.global_tilted_irradiance?.[index]==null?null:Number(hourly.global_tilted_irradiance[index])})); }

function Scheduler({ language }: { language: "ur"|"en" }) {
  const ur=language==="ur"; const appliances=readLocal<Appliance[]>(APPLIANCES_KEY,DEFAULT_APPLIANCES); const settings=readLocal<SolarForecastSettings|null>(FORECAST_SETTINGS_KEY,null); const [best,setBest]=useState<{today:ForecastHour|null;tomorrow:ForecastHour|null}>({today:null,tomorrow:null});
  useEffect(()=>{if(!settings)return;const timer=window.setTimeout(async()=>{const query=new URLSearchParams({latitude:String(settings.latitude),longitude:String(settings.longitude),tilt:String(settings.roofTilt),azimuth:String(ORIENTATION_AZIMUTH[settings.orientation])});try{const response=await fetch(`/api/forecast/weather?${query}`);if(!response.ok)return;const json=await response.json() as {hourly:Record<string,Array<string|number>>;daily:{sunrise:string[];sunset:string[]}};const source=apiWeatherHours(json.hourly);const today=calculateForecast(settings,source,json.daily.sunrise[0],json.daily.sunset[0],1).sort((a,b)=>b.outputKw-a.outputKw)[0]??null;const tomorrow=json.daily.sunrise[1]?calculateForecast(settings,source,json.daily.sunrise[1],json.daily.sunset[1],1).sort((a,b)=>b.outputKw-a.outputKw)[0]??null:null;setBest({today,tomorrow});}catch{/* weather error is represented by empty state */}},0);return()=>window.clearTimeout(timer);},[settings]);
  const time=(hour:ForecastHour|null)=>hour?new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit"}).format(new Date(hour.time)):"—"; const confidence=(hour:ForecastHour|null)=>hour?Math.max(35,Math.round(100-hour.cloudCover*.45-hour.precipitationProbability*.25)):0;
  return <Section title={ur?"سمارٹ شیڈولر":"Smart scheduler"} hint={ur?"موسم اور متوقع سولر کے مطابق بہترین وقت۔":"Best operating windows calculated from weather and tilted-panel irradiance."}>{settings?<div className="space-y-2">{appliances.filter(a=>a.watts>=500).map((item,index)=><div key={item.id} className="grid gap-4 rounded-2xl border border-white/[.07] p-4 sm:grid-cols-[1fr_auto]"><div><p className="font-medium text-white">{applianceNames[language][item.id]??item.name}</p><p className="mt-1 text-xs text-slate-500">{ur?"مدت":"Duration"}: {item.watts>=1000?"20":"30"} min · {ur?"ترجیح":"Priority"}: {index<2?(ur?"زیادہ":"High"):(ur?"عام":"Normal")}</p></div><div className="grid grid-cols-2 gap-4 text-end"><div><p className="text-[10px] text-slate-600">{ur?"آج":"Today"}</p><p className="text-sm font-semibold text-emerald-300">{time(best.today)}</p><p className="text-[10px] text-slate-500">{best.today?.outputKw.toFixed(1)??"—"} kW · {confidence(best.today)}%</p></div><div><p className="text-[10px] text-slate-600">{ur?"کل":"Tomorrow"}</p><p className="text-sm font-semibold text-violet-300">{time(best.tomorrow)}</p><p className="text-[10px] text-slate-500">{best.tomorrow?.outputKw.toFixed(1)??"—"} kW · {confidence(best.tomorrow)}%</p></div></div></div>)}</div>:<Empty text={ur?"پہلے سولر پیشگوئی سیٹ کریں۔":"Set up Solar Forecast first."}/>}</Section>;
}

function Analytics({ language }: { language:"ur"|"en" }) { const ur=language==="ur"; const [range,setRange]=useState<"day"|"week"|"month"|"year">("day"); const points=readLocal<EnergyHistoryPoint[]>(ENERGY_HISTORY_KEY,[]); const chart=aggregateHistory(points,range); const max=Math.max(...chart.flatMap(p=>[p.pvKw,p.loadKw]),.1); const download=()=>{const blob=new Blob([historyCsv(points)],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="knox-energy-history.csv";a.click();URL.revokeObjectURL(url);}; return <Section title={ur?"تاریخی تجزیات":"Historical analytics"} hint={ur?"ریکارڈنگ اب سے مقامی طور پر محفوظ ہوتی ہے۔":"Local history is recorded from now onward."}><div className="flex flex-wrap gap-2">{(["day","week","month","year"] as const).map(r=><button key={r} onClick={()=>setRange(r)} className={`rounded-full px-3 py-1.5 text-xs ${range===r?"bg-white text-black":"bg-white/[.05] text-slate-500"}`}>{r}</button>)}<button onClick={()=>window.print()} className="ms-auto rounded-full border border-white/[.08] px-3 text-xs text-slate-400">PDF</button><button onClick={download} className="rounded-full border border-white/[.08] px-3 text-xs text-slate-400">CSV</button></div>{chart.length?<div className="mt-6 flex h-56 items-end gap-1">{chart.map(point=><div key={point.time} className="flex min-w-0 flex-1 items-end gap-px"><div className="flex-1 rounded-t bg-amber-300/70" style={{height:`${point.pvKw/max*100}%`}}/><div className="flex-1 rounded-t bg-sky-400/55" style={{height:`${point.loadKw/max*100}%`}}/></div>)}</div>:<Empty text={ur?"تاریخی ڈیٹا جمع ہو رہا ہے۔":"History is being collected. Check back after the dashboard has run for a while."}/>}</Section>; }

function Health({data,language}:{data:LiveData;language:"ur"|"en"}) {const ur=language==="ur";const result=healthScore(data,readLocal(ENERGY_HISTORY_KEY,[]));return <Section title={ur?"سولر صحت":"Solar health"} hint={ur?"صرف حقیقی انورٹر ڈیٹا سے۔":"Calculated only from measured inverter data."}><div className="flex items-center gap-5 rounded-3xl border border-emerald-400/15 bg-emerald-400/[.05] p-6"><div className="text-5xl font-semibold text-white">{result.score}%</div><div><p className="font-semibold text-emerald-300">{result.label}</p><p className="mt-1 text-xs text-slate-500">{ur?"مجموعی صحت اسکور":"Overall health score"}</p></div></div><div className="mt-4 space-y-2">{result.reasons.map(reason=><p key={reason} className="rounded-xl bg-white/[.03] p-3 text-sm text-slate-400">• {reason}</p>)}</div></Section>}

function Alerts({language}:{language:"ur"|"en"}) {const ur=language==="ur";const [rules,setRules]=useState<NotificationRules>(()=>({...DEFAULT_RULES,...readLocal(ENERGY_RULES_KEY,DEFAULT_RULES)}));const save=(next:NotificationRules)=>{setRules(next);localStorage.setItem(ENERGY_RULES_KEY,JSON.stringify(next));};const enable=async()=>{if("Notification" in window) await Notification.requestPermission();save({...rules,enabled:true});};return <Section title={ur?"سمارٹ اطلاعات":"Smart notifications"} hint={ur?"براؤزر اجازت کے بعد مقامی اطلاعات۔":"Local browser alerts after permission is granted."}><Toggle label={ur?"اطلاعات فعال":"Enable notifications"} value={rules.enabled} onChange={value=>value?void enable():save({...rules,enabled:false})}/><Rule label={ur?"سولر اس سے زیادہ ہو":"Solar exceeds"} value={rules.solarAboveKw} onChange={value=>save({...rules,solarAboveKw:value})}/><Rule label={ur?"اضافی سولر اس سے زیادہ ہو":"Surplus exceeds"} value={rules.surplusAboveKw} onChange={value=>save({...rules,surplusAboveKw:value})}/><Rule label={ur?"اچانک کمی فیصد":"Sudden production drop"} value={rules.suddenDropPercent} suffix="%" onChange={value=>save({...rules,suddenDropPercent:value})}/><Toggle label={ur?"آلہ محفوظ طریقے سے چل سکے":"An appliance can safely run"} value={rules.applianceReady} onChange={value=>save({...rules,applianceReady:value})}/><Toggle label={ur?"بادل آنے سے پہلے":"Before clouds arrive"} value={rules.cloudsAhead} onChange={value=>save({...rules,cloudsAhead:value})}/><Toggle label={ur?"انورٹر منقطع ہو":"Inverter disconnects"} value={rules.inverterOffline} onChange={value=>save({...rules,inverterOffline:value})}/></Section>}

function Sites({language}:{language:"ur"|"en"}) {const ur=language==="ur";const [sites,setSites]=useState<EnergySite[]>(()=>readLocal(ENERGY_SITES_KEY,[]));const add=()=>{const name=window.prompt(ur?"مقام کا نام":"Site name");if(!name)return;const next=[...sites,{id:crypto.randomUUID(),name,type:"home" as const,forecast:readLocal(FORECAST_SETTINGS_KEY,null),appliances:readLocal(APPLIANCES_KEY,DEFAULT_APPLIANCES)}];setSites(next);localStorage.setItem(ENERGY_SITES_KEY,JSON.stringify(next));};const activate=(site:EnergySite)=>{if(site.forecast)localStorage.setItem(FORECAST_SETTINGS_KEY,JSON.stringify(site.forecast));localStorage.setItem(APPLIANCES_KEY,JSON.stringify(site.appliances));};return <Section title={ur?"متعدد مقامات":"Multi-site"} hint={ur?"گھر، فارم، دفتر یا گودام کی ترتیبات محفوظ کریں۔":"Save and switch separate Home, Farm, Office, or Warehouse profiles."}><button onClick={add} className="btn-solar">+ {ur?"مقام شامل کریں":"Add site"}</button><div className="mt-4 space-y-2">{sites.map(site=><div key={site.id} className="flex items-center justify-between rounded-2xl border border-white/[.07] p-4"><div><p className="font-medium text-white">{site.name}</p><p className="text-xs capitalize text-slate-600">{site.type} · {site.forecast?`${site.forecast.panels} panels`:(ur?"سیٹ اپ نہیں":"Not configured")}</p></div><button onClick={()=>activate(site)} className="rounded-full bg-white/[.06] px-3 py-1.5 text-xs text-emerald-300">{ur?"منتخب کریں":"Activate"}</button></div>)}</div></Section>}

function Section({title,hint,children}:{title:string;hint:string;children:React.ReactNode}){return <section><h3 className="text-2xl font-semibold text-white">{title}</h3><p className="mt-2 text-sm text-slate-500">{hint}</p><div className="mt-6">{children}</div></section>}
function Stat({label,value,tone}:{label:string;value:string;tone?:"good"|"bad"}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-600">{label}</p><p className={`mt-2 text-xl font-semibold ${tone==="good"?"text-emerald-300":tone==="bad"?"text-red-300":"text-white"}`}>{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/[.1] p-8 text-center text-sm text-slate-500">{text}</div>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="mb-2 flex items-center justify-between rounded-2xl border border-white/[.07] p-4 text-sm text-slate-300"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)} className="h-5 w-5 accent-emerald-400"/></label>}
function Rule({label,value,onChange,suffix="kW"}:{label:string;value:number;onChange:(v:number)=>void;suffix?:string}){return <label className="mb-2 flex items-center justify-between gap-4 rounded-2xl border border-white/[.07] p-4 text-sm text-slate-300"><span>{label}</span><span className="flex items-center gap-2"><input type="number" step=".1" value={value} onChange={e=>onChange(Number(e.target.value))} className="w-20 rounded-lg bg-black/20 p-2 text-end text-white outline-none"/>{suffix}</span></label>}
